site_name: TOAD
theme: flatly
pages:
- [index.md, Home]
- [tuto/01-prerequis.md, Tutoriel, 01-Pré-requis]
- [tuto/02-prepdata.md, Tutoriel, 02-Préparation des données]
- [tuto/03-toadtuto.md, Tutoriel, 03-TOAD]
- [tuto/04-visualisation.md, Tutoriel, 04-Visualisation]
- [qa/01-QA_T1.md, QA, 01-Anatomy]
- [qa/02-QA_DWI.md, QA, 02-Diffusion]
- [qa/03-QA_XX.md, QA, 03-Registration]
- [tasks/01-Preparation.md, Tâches, 01-Preparation]
- [tasks/02-Unwarping.md, Tâches, 02-Unwarping]
- [tasks/03-Denoising.md, Tâches, 03-Denoising]
- [tasks/04-Preprocessing.md, Tâches, 04-Preprocessing]
- [tasks/05-Parcellation.md, Tâches, 05-Parcellation]
- [tasks/06-Registration.md, Tâches, 06-Registration]
- [tasks/07-Masking.md, Tâches, 07-Masking]
- [tasks/08-Dtifit.md, Tâches, 08-Dtifit]
- [tasks/09-Tensors.md, Tâches, 09-Tensors]
- [tasks/10-Tensorsmetric.md, Tâches, 10-Tensorsmetric]
- [tasks/11-Tensorstractography.md, Tâches, 11-Tensorstractography]
- [tasks/12-Hardi.md, Tâches, 12-Hardi]
- [tasks/13-Hardimetric.md, Tâches, 13-Hardimetric]
- [tasks/14-Harditractography.md, Tâches, 14-Harditractography]
- [tasks/15-Qa.md, Tâches, 15-Qa]
